name: Test
on:
  pull_request:
  push:
jobs:
  test:
    name: Build and test
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v3
          with:
            go-version: '^1.18.2'
        - run: go test
